NAME_OF_THE_GAME = "Battle of the guardians"
WIDTH, HEIGHT = 1000, 1000
FRAME_RATE = 1000
BATTLE_BUTTON_COORDINATES = (WIDTH / 2, HEIGHT / 2)
VS_BUTTON_COORDINATES = (WIDTH / 2, HEIGHT / 2)
RELATIVE_BATTLE_BUTTON_SIZE = 0.4
RELATIVE_VS_BUTTON_SIZE = 0.2
BATTLE_BUTTON_SIZE = (WIDTH * RELATIVE_BATTLE_BUTTON_SIZE, HEIGHT * RELATIVE_BATTLE_BUTTON_SIZE)
VS_BUTTON_SIZE = (WIDTH * RELATIVE_VS_BUTTON_SIZE, HEIGHT * RELATIVE_VS_BUTTON_SIZE)
CARD_SIZE = (180, 320)
BASIC_OUTLINE_THICKNESS = (45, 52)
NUMBER_OF_CARDS = 8
LEFT_DRAFT_CARD_COORDINATES = (WIDTH / 4, HEIGHT / 2)
RIGHT_DRAFT_CARD_COORDINATES = (WIDTH * 3 / 4, HEIGHT / 2)
ALL_CARD_COORDINATES = [(WIDTH / 5, HEIGHT / 3 * 2),
                        (WIDTH / 5 * 2, HEIGHT / 3 * 2),
                        (WIDTH / 5 * 3, HEIGHT / 3 * 2),
                        (WIDTH / 5 * 4, HEIGHT / 3 * 2)]
FIRE_WIZARD_HP = 5000
FIRE_WIZARD_DMG = 3000
FIRE_DRAGON_HP = 8000
FIRE_DRAGON_DMG = 5000
ICE_WIZARD_HP = 4000
ICE_WIZARD_DMG = 2000
MERMAID_HP = 6000
MERMAID_DMG = 3000
GROUND_TITAN_HP = 10000
GROUND_TITAN_DMG = 4000
STONE_DWARF_HP = 5000
STONE_DWARF_DMG = 3000
BLAZING_HERALD_HP = 4000
BLAZING_HERALD_DMG = 4000
ELECTRO_WIZARD_HP = 6000
ELECTRO_WIZARD_DMG = 5000
SHADOW_MONSTER_HP = 3000
SHADOW_MONSTER_DMG = 1000

DEFAULT_HP_BAR_SIZE = (CARD_SIZE[0], CARD_SIZE[1] / 10)

DISTANCE_BETWEEN_CARD_AND_HP_BAR = CARD_SIZE[0] / 10

DEFAULT_HP_BAR_THICKNESS = (5, 4)

MAXIMUM_AMOUNT_OF_HITPOINTS_IN_DEFAULT_HP_BAR = int((DEFAULT_HP_BAR_SIZE[0] - 2 * DEFAULT_HP_BAR_THICKNESS[0]) / (DEFAULT_HP_BAR_SIZE[1] - DEFAULT_HP_BAR_THICKNESS[1] * 2))

FANTASY_FONT_SIZE = HEIGHT / 10

WAVES_COUNTER_RIGHT_CORNER_POS = (WIDTH, 0)