NAME_OF_THE_GAME: str = "Battle of the guardians"
DEFAULT_WIDTH: int = 1000
DEFAULT_HEIGHT: int = 1000
MAX_WIDTH: int = 1980
MAX_HEIGHT: int = 1080
FRAME_RATE: int = 1000
RELATIVE_BATTLE_BUTTON_COORDINATES: tuple[float, float] = (0.5, 0.5)
RELATIVE_VS_BUTTON_COORDINATES: tuple[float, float] = (0.5, 0.5)
RELATIVE_BATTLE_BUTTON_SIZE: tuple[float, float] = (0.4, 0.4)
RELATIVE_VS_BUTTON_SIZE: tuple[float, float] = (0.2, 0.2)
RELATIVE_CARD_SIZE: tuple[float, float] = (9 / 50, 8 / 25)
RELATIVE_BASIC_OUTLINE_THICKNESS: tuple[float, float] = (21 / 500, 29 / 500)
NUMBER_OF_CARDS: int = 8
RELATIVE_LEFT_DRAFT_CARD_COORDINATES: tuple[float, float] = (0.25, 0.5)
RELATIVE_RIGHT_DRAFT_CARD_COORDINATES: tuple[float, float] = (0.75, 0.5)
RELATIVE_DISTANCE_BETWEEN_CARDS = (1 - RELATIVE_CARD_SIZE[0] * 4) / 5
ALL_CARD_COORDINATES: list[tuple[float, float]] = [(RELATIVE_DISTANCE_BETWEEN_CARDS + RELATIVE_CARD_SIZE[0] / 2, 1 / 3 * 2),
                             (RELATIVE_DISTANCE_BETWEEN_CARDS * 2 + RELATIVE_CARD_SIZE[0] / 2 * 3, 2 / 3),
                             (RELATIVE_DISTANCE_BETWEEN_CARDS * 3 + RELATIVE_CARD_SIZE[0] / 2 * 5, 2 / 3),
                             (RELATIVE_DISTANCE_BETWEEN_CARDS * 4 + RELATIVE_CARD_SIZE[0] / 2 * 7, 2 / 3)]
FIRE_WIZARD_HP = 5000
FIRE_WIZARD_DMG = 3000
FIRE_DRAGON_HP = 8000
FIRE_DRAGON_DMG = 5000
ICE_WIZARD_HP = 4000
ICE_WIZARD_DMG = 2000
MERMAID_HP = 6000
MERMAID_DMG = 3000
GROUND_TITAN_HP = 10000
GROUND_TITAN_DMG = 4000
STONE_DWARF_HP = 5000
STONE_DWARF_DMG = 3000
BLAZING_HERALD_HP = 4000
BLAZING_HERALD_DMG = 4000
ELECTRO_WIZARD_HP = 6000
ELECTRO_WIZARD_DMG = 5000
SHADOW_MONSTER_HP = 3000
SHADOW_MONSTER_DMG = 1000

RELATIVE_DEFAULT_HP_BAR_SIZE: tuple[float, float] = (RELATIVE_CARD_SIZE[0], RELATIVE_CARD_SIZE[1] / 10)

RELATIVE_DISTANCE_BETWEEN_CARD_AND_HP_BAR: float = RELATIVE_CARD_SIZE[0] / 10

RELATIVE_DEFAULT_HP_BAR_THICKNESS: tuple[float, float] = (RELATIVE_DEFAULT_HP_BAR_SIZE[0] / 36, RELATIVE_DEFAULT_HP_BAR_SIZE[1] / 8)

MAXIMUM_AMOUNT_OF_HITPOINTS_IN_DEFAULT_HP_BAR = int(RELATIVE_DEFAULT_HP_BAR_SIZE[0] * MAX_WIDTH)

RELATIVE_FANTASY_FONT_FOR_WAVES_COUNTER_SIZE: float = 0.1

RELATIVE_FANTASY_FONT_FOR_CARD_HEALTH_SIZE_USING_THE_DEFAULT_HP_BAR: float = RELATIVE_DEFAULT_HP_BAR_SIZE[1]

RELATIVE_WAVES_COUNTER_RIGHT_CORNER_POS: tuple[float, float] = (1, 0)

RELATIVE_HITPOINTS_ICON_SIZE: float = 1.3

RELATIVE_DEFAULT_ENERGY_BAR_SIZE: tuple[float, float] = (0.5, 0.1)
